import type { ProcessTask } from "@/lib/models/process-task";

export const corporateAccountOpeningProcessTasks: ProcessTask[] = [
  {
    id: "corp-account-000",
    stepId: "C000",
    parentStepId: null,
    rowType: "start",
    bpmnType: "startEvent",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Start",
    actor: "System",
    actorLane: "System",
    system: "Corporate Onboarding Portal",
    systemLane: "Digital Channel",
    dataObject: "",
    dataAction: "none",
    taskName: "Corporate account opening journey starts",
    input: "Corporate customer opens onboarding portal",
    output: "Account opening journey started",
    defaultNextStep: "C001",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Portal session is tracked",
    sourceRef: "CAO-START-000",
    reviewStatus: "draft",
    comment: "Start event for corporate account opening",
    customerInteractionType: "Support Process",
    channel: "Portal"
  },
  {
    id: "corp-account-001",
    stepId: "C001",
    parentStepId: "C000",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Application Intake",
    group: "Customer Submission",
    actor: "Customer",
    actorLane: "Customer",
    system: "Corporate Onboarding Portal",
    systemLane: "Digital Channel",
    dataObject: "Corporate application form",
    dataAction: "create",
    taskName: "Customer enters corporate profile",
    input: "Company registration details and contact information",
    output: "Draft corporate application",
    defaultNextStep: "C002",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Customer abandons portal session",
    exceptionHandling: "Save draft and send reminder if contact details exist",
    sla: "30 minutes",
    riskControl: "Mandatory field validation on company identifiers",
    sourceRef: "CAO-INTAKE-001",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Customer Action",
    channel: "Portal"
  },
  {
    id: "corp-account-002",
    stepId: "C002",
    parentStepId: "C001",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Application Intake",
    group: "Customer Submission",
    actor: "Customer",
    actorLane: "Customer",
    system: "Corporate Onboarding Portal",
    systemLane: "Digital Channel",
    dataObject: "KYC document package",
    dataAction: "push",
    taskName: "Customer uploads incorporation and KYC documents",
    input: "Business license, tax certificate, authorized signer IDs",
    output: "Uploaded document package",
    defaultNextStep: "C003",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Unsupported file format",
    exceptionHandling: "Show accepted formats and request re-upload",
    sla: "30 minutes",
    riskControl: "File type and malware scan before storage",
    sourceRef: "CAO-INTAKE-002",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Customer Action",
    channel: "Portal"
  },
  {
    id: "corp-account-003",
    stepId: "C003",
    parentStepId: "C002",
    rowType: "data",
    bpmnType: "dataObject",
    taskNature: "data",
    phase: "Application Intake",
    group: "Data Capture",
    actor: "System",
    actorLane: "System",
    system: "Document Store",
    systemLane: "Document Store",
    dataObject: "KYC document package",
    dataAction: "store",
    taskName: "Store uploaded KYC document package",
    input: "Uploaded document package",
    output: "Document package stored with reference ID",
    defaultNextStep: "C004",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Storage failure",
    exceptionHandling: "Retry storage and flag case for operations support",
    sla: "Immediate",
    riskControl: "Document checksum and access control",
    sourceRef: "CAO-DATA-003",
    reviewStatus: "draft",
    comment: "Data interaction row for document storage",
    customerInteractionType: "Data / Control",
    channel: "Document Store"
  },
  {
    id: "corp-account-004",
    stepId: "C004",
    parentStepId: "C003",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Initial Validation",
    group: "System Validation",
    actor: "System",
    actorLane: "System",
    system: "KYC Validation Service",
    systemLane: "KYC Platform",
    dataObject: "Corporate registry data",
    dataAction: "pull",
    taskName: "Validate company registration against registry",
    input: "Company registration number and legal name",
    output: "Registry validation result",
    defaultNextStep: "C005",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Registry service unavailable",
    exceptionHandling: "Place case in manual validation queue",
    sla: "5 minutes",
    riskControl: "Registry match required before onboarding continues",
    sourceRef: "CAO-VALIDATE-004",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Back-stage System",
    channel: "Internal System"
  },
  {
    id: "corp-account-005",
    stepId: "C005",
    parentStepId: "C004",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "decision",
    phase: "Initial Validation",
    group: "Eligibility Decision",
    actor: "System",
    actorLane: "System",
    system: "KYC Validation Service",
    systemLane: "KYC Platform",
    dataObject: "Registry validation result",
    dataAction: "validate",
    taskName: "Is company registry validation successful?",
    input: "Registry validation result",
    output: "Registry decision",
    defaultNextStep: null,
    conditionQuestion: "Is company registry validation successful?",
    yesNextStep: "C006",
    noNextStep: "C020",
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Failed registry validation cannot proceed automatically",
    sourceRef: "CAO-GW-005",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Data / Control",
    channel: "Internal System"
  },
  {
    id: "corp-account-006",
    stepId: "C006",
    parentStepId: "C005",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Relationship Review",
    group: "RM Review",
    actor: "RM",
    actorLane: "Relationship Manager",
    system: "CRM",
    systemLane: "CRM",
    dataObject: "Corporate application form",
    dataAction: "read",
    taskName: "RM reviews corporate relationship context",
    input: "Draft application and customer relationship notes",
    output: "RM review comments",
    defaultNextStep: "C007",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "RM identifies missing business context",
    exceptionHandling: "Request clarification from customer before operations review",
    sla: "1 business day",
    riskControl: "Relationship review required for corporate onboarding",
    sourceRef: "CAO-RM-006",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Front-stage People",
    channel: "RM Meeting"
  },
  {
    id: "corp-account-007",
    stepId: "C007",
    parentStepId: "C006",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "decision",
    phase: "Relationship Review",
    group: "Document Completeness",
    actor: "RM",
    actorLane: "Relationship Manager",
    system: "CRM",
    systemLane: "CRM",
    dataObject: "KYC document package",
    dataAction: "validate",
    taskName: "Are required onboarding documents complete?",
    input: "RM review comments and document checklist",
    output: "Document completeness decision",
    defaultNextStep: null,
    conditionQuestion: "Are required onboarding documents complete?",
    yesNextStep: "C008",
    noNextStep: "C021",
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Incomplete documents cannot proceed to screening",
    sourceRef: "CAO-GW-007",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Back-stage People",
    channel: "Internal System"
  },
  {
    id: "corp-account-008",
    stepId: "C008",
    parentStepId: "C007",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "KYC Screening",
    group: "Screening",
    actor: "System",
    actorLane: "System",
    system: "Sanctions Screening Engine",
    systemLane: "Compliance Platform",
    dataObject: "Beneficial owner data",
    dataAction: "validate",
    taskName: "Run sanctions and PEP screening",
    input: "Company, directors, authorized signers, beneficial owners",
    output: "Screening result",
    defaultNextStep: "C009",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Screening engine timeout",
    exceptionHandling: "Retry and route to manual compliance queue if timeout persists",
    sla: "10 minutes",
    riskControl: "Screen all related parties before account creation",
    sourceRef: "CAO-SCREEN-008",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Back-stage System",
    channel: "Internal System"
  },
  {
    id: "corp-account-009",
    stepId: "C009",
    parentStepId: "C008",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "decision",
    phase: "KYC Screening",
    group: "Screening Decision",
    actor: "System",
    actorLane: "System",
    system: "Sanctions Screening Engine",
    systemLane: "Compliance Platform",
    dataObject: "Screening result",
    dataAction: "validate",
    taskName: "Is screening clear?",
    input: "Screening result",
    output: "Screening decision",
    defaultNextStep: null,
    conditionQuestion: "Is screening clear?",
    yesNextStep: "C010",
    noNextStep: "C023",
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Positive hits require compliance review",
    sourceRef: "CAO-GW-009",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Data / Control",
    channel: "Internal System"
  },
  {
    id: "corp-account-010",
    stepId: "C010",
    parentStepId: "C009",
    rowType: "data",
    bpmnType: "dataStore",
    taskNature: "data",
    phase: "KYC Screening",
    group: "KYC Record",
    actor: "System",
    actorLane: "System",
    system: "KYC Repository",
    systemLane: "KYC Platform",
    dataObject: "KYC screening record",
    dataAction: "store",
    taskName: "Store approved KYC screening record",
    input: "Clear screening result",
    output: "KYC screening record stored",
    defaultNextStep: "C011",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "KYC repository write failure",
    exceptionHandling: "Retry write and notify operations support",
    sla: "Immediate",
    riskControl: "Immutable screening result is retained",
    sourceRef: "CAO-DATA-010",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Data / Control",
    channel: "Internal System"
  },
  {
    id: "corp-account-011",
    stepId: "C011",
    parentStepId: "C010",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Operations Review",
    group: "Document Verification",
    actor: "Ops",
    actorLane: "Operations",
    system: "Onboarding Workflow",
    systemLane: "Workflow",
    dataObject: "KYC document package",
    dataAction: "read",
    taskName: "Ops verifies documents and signer authority",
    input: "Stored documents and KYC screening record",
    output: "Operations verification result",
    defaultNextStep: "C012",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Document authenticity concern",
    exceptionHandling: "Escalate to compliance and request original documents",
    sla: "1 business day",
    riskControl: "Four-eyes review for signer authority",
    sourceRef: "CAO-OPS-011",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Back-stage People",
    channel: "Internal System"
  },
  {
    id: "corp-account-012",
    stepId: "C012",
    parentStepId: "C011",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Account Creation",
    group: "Core Banking",
    actor: "System",
    actorLane: "System",
    system: "Core Banking System",
    systemLane: "Core Banking",
    dataObject: "Corporate account master",
    dataAction: "create",
    taskName: "Create corporate account in core banking",
    input: "Approved onboarding data and account product setup",
    output: "Corporate account number",
    defaultNextStep: "C013",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Core banking account creation error",
    exceptionHandling: "Create exception case for operations resolution",
    sla: "15 minutes",
    riskControl: "Account creation uses approved KYC record only",
    sourceRef: "CAO-CORE-012",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Back-stage System",
    channel: "Internal System"
  },
  {
    id: "corp-account-013",
    stepId: "C013",
    parentStepId: "C012",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "decision",
    phase: "Account Creation",
    group: "Core Banking",
    actor: "System",
    actorLane: "System",
    system: "Core Banking System",
    systemLane: "Core Banking",
    dataObject: "Corporate account master",
    dataAction: "validate",
    taskName: "Was account created successfully?",
    input: "Core banking response",
    output: "Account creation decision",
    defaultNextStep: null,
    conditionQuestion: "Was account created successfully?",
    yesNextStep: "C014",
    noNextStep: "C024",
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Failed creation requires manual resolution before activation",
    sourceRef: "CAO-GW-013",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Data / Control",
    channel: "Internal System"
  },
  {
    id: "corp-account-014",
    stepId: "C014",
    parentStepId: "C013",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "approval",
    phase: "Final Approval",
    group: "Approval",
    actor: "Approver",
    actorLane: "Approver",
    system: "Onboarding Workflow",
    systemLane: "Workflow",
    dataObject: "Corporate account opening case",
    dataAction: "approve",
    taskName: "Approver reviews and approves account activation",
    input: "Operations verification result and account number",
    output: "Activation approval decision",
    defaultNextStep: "C015",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Approver requests additional clarification",
    exceptionHandling: "Return case to RM or Ops with comments",
    sla: "1 business day",
    riskControl: "Approval required before channel activation",
    sourceRef: "CAO-APPROVE-014",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Back-stage People",
    channel: "Internal System"
  },
  {
    id: "corp-account-015",
    stepId: "C015",
    parentStepId: "C014",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "decision",
    phase: "Final Approval",
    group: "Approval",
    actor: "Approver",
    actorLane: "Approver",
    system: "Onboarding Workflow",
    systemLane: "Workflow",
    dataObject: "Activation approval decision",
    dataAction: "validate",
    taskName: "Is account activation approved?",
    input: "Approver decision",
    output: "Activation decision",
    defaultNextStep: null,
    conditionQuestion: "Is account activation approved?",
    yesNextStep: "C016",
    noNextStep: "C025",
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Rejected activation prevents account use",
    sourceRef: "CAO-GW-015",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Data / Control",
    channel: "Internal System"
  },
  {
    id: "corp-account-016",
    stepId: "C016",
    parentStepId: "C015",
    rowType: "data",
    bpmnType: "dataStore",
    taskNature: "data",
    phase: "Activation",
    group: "Account Master",
    actor: "System",
    actorLane: "System",
    system: "Core Banking System",
    systemLane: "Core Banking",
    dataObject: "Corporate account master",
    dataAction: "store",
    taskName: "Store activated corporate account master",
    input: "Approved account and activation decision",
    output: "Activated account master stored",
    defaultNextStep: "C017",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Account status update failure",
    exceptionHandling: "Retry update and notify operations support",
    sla: "Immediate",
    riskControl: "Activation status change is audited",
    sourceRef: "CAO-DATA-016",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Data / Control",
    channel: "Internal System"
  },
  {
    id: "corp-account-017",
    stepId: "C017",
    parentStepId: "C016",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "notification",
    phase: "Activation",
    group: "Customer Notification",
    actor: "System",
    actorLane: "System",
    system: "Notification Service",
    systemLane: "Notification Service",
    dataObject: "Account opening notification",
    dataAction: "send",
    taskName: "Send account opening confirmation to customer",
    input: "Activated account number and onboarding contacts",
    output: "Customer confirmation sent",
    defaultNextStep: "C018",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Notification delivery failure",
    exceptionHandling: "Retry delivery and create manual follow-up task",
    sla: "Immediate",
    riskControl: "Notification content excludes sensitive credentials",
    sourceRef: "CAO-NOTIFY-017",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Front-stage System",
    channel: "Email"
  },
  {
    id: "corp-account-018",
    stepId: "C018",
    parentStepId: "C017",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Activation",
    group: "Channel Setup",
    actor: "System",
    actorLane: "System",
    system: "Digital Banking Platform",
    systemLane: "Digital Channel",
    dataObject: "Digital banking access profile",
    dataAction: "create",
    taskName: "Enable corporate digital banking access",
    input: "Activated account and authorized signer profile",
    output: "Digital banking access enabled",
    defaultNextStep: "C019",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Digital banking provisioning failure",
    exceptionHandling: "Queue retry and notify RM",
    sla: "30 minutes",
    riskControl: "Access provisioning follows signer authority matrix",
    sourceRef: "CAO-CHANNEL-018",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Front-stage System",
    channel: "Mobile App"
  },
  {
    id: "corp-account-019",
    stepId: "C019",
    parentStepId: "C018",
    rowType: "end",
    bpmnType: "endEvent",
    taskNature: "automatic",
    phase: "Activation",
    group: "End",
    actor: "System",
    actorLane: "System",
    system: "Onboarding Workflow",
    systemLane: "Workflow",
    dataObject: "Corporate account opening case",
    dataAction: "update",
    taskName: "Corporate account opened and activated",
    input: "Activated account and enabled channels",
    output: "Account opening journey completed",
    defaultNextStep: null,
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Case completion is audited",
    sourceRef: "CAO-END-019",
    reviewStatus: "draft",
    comment: "Successful end state",
    customerInteractionType: "Support Process",
    channel: "Internal System"
  },
  {
    id: "corp-account-020",
    stepId: "C020",
    parentStepId: "C005",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "notification",
    phase: "Initial Validation",
    group: "Customer Notification",
    actor: "System",
    actorLane: "System",
    system: "Notification Service",
    systemLane: "Notification Service",
    dataObject: "Registry validation failure notice",
    dataAction: "send",
    taskName: "Notify customer that registry validation failed",
    input: "Failed registry validation result",
    output: "Registry failure notification sent",
    defaultNextStep: "C026",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Notification delivery failure",
    exceptionHandling: "Create manual follow-up for RM",
    sla: "Immediate",
    riskControl: "Do not disclose internal registry matching logic",
    sourceRef: "CAO-NOTIFY-020",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Front-stage System",
    channel: "Email"
  },
  {
    id: "corp-account-021",
    stepId: "C021",
    parentStepId: "C007",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "notification",
    phase: "Relationship Review",
    group: "Supplement Request",
    actor: "RM",
    actorLane: "Relationship Manager",
    system: "CRM",
    systemLane: "CRM",
    dataObject: "Supplement request",
    dataAction: "send",
    taskName: "RM requests missing onboarding documents",
    input: "Document completeness decision and missing document list",
    output: "Supplement request sent to customer",
    defaultNextStep: "C022",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Customer contact unavailable",
    exceptionHandling: "Attempt phone follow-up and mark case pending",
    sla: "Same business day",
    riskControl: "Request only documents required by policy",
    sourceRef: "CAO-SUPPLEMENT-021",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Front-stage People",
    channel: "Email"
  },
  {
    id: "corp-account-022",
    stepId: "C022",
    parentStepId: "C021",
    rowType: "end",
    bpmnType: "endEvent",
    taskNature: "automatic",
    phase: "Relationship Review",
    group: "Pending End",
    actor: "System",
    actorLane: "System",
    system: "Onboarding Workflow",
    systemLane: "Workflow",
    dataObject: "Corporate account opening case",
    dataAction: "update",
    taskName: "Case paused pending customer supplement",
    input: "Supplement request sent",
    output: "Case status set to pending supplement",
    defaultNextStep: null,
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Pending cases are monitored for expiry",
    sourceRef: "CAO-END-022",
    reviewStatus: "draft",
    comment: "Pause end state for missing documents",
    customerInteractionType: "Support Process",
    channel: "Internal System"
  },
  {
    id: "corp-account-023",
    stepId: "C023",
    parentStepId: "C009",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "control",
    phase: "KYC Screening",
    group: "Compliance Review",
    actor: "Ops",
    actorLane: "Operations",
    system: "Compliance Case Manager",
    systemLane: "Compliance Platform",
    dataObject: "Screening hit case",
    dataAction: "validate",
    taskName: "Ops reviews screening hit and recommends outcome",
    input: "Potential sanctions or PEP hit",
    output: "Compliance review outcome",
    defaultNextStep: "C025",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Potential true hit",
    exceptionHandling: "Escalate to compliance approver outside standard onboarding flow",
    sla: "1 business day",
    riskControl: "Manual review required for all positive hits",
    sourceRef: "CAO-COMP-023",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Back-stage People",
    channel: "Internal System"
  },
  {
    id: "corp-account-024",
    stepId: "C024",
    parentStepId: "C013",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Account Creation",
    group: "Exception Handling",
    actor: "Ops",
    actorLane: "Operations",
    system: "Onboarding Workflow",
    systemLane: "Workflow",
    dataObject: "Core banking exception",
    dataAction: "update",
    taskName: "Ops resolves account creation exception",
    input: "Core banking error and approved onboarding data",
    output: "Resolved account creation exception",
    defaultNextStep: "C012",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Exception cannot be resolved",
    exceptionHandling: "Escalate to technology support and keep case on hold",
    sla: "1 business day",
    riskControl: "Manual correction is audited",
    sourceRef: "CAO-EXCEPTION-024",
    reviewStatus: "draft",
    comment: "Loops back to account creation after resolution",
    customerInteractionType: "Back-stage People",
    channel: "Internal System"
  },
  {
    id: "corp-account-025",
    stepId: "C025",
    parentStepId: "C015",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "notification",
    phase: "Final Approval",
    group: "Customer Notification",
    actor: "System",
    actorLane: "System",
    system: "Notification Service",
    systemLane: "Notification Service",
    dataObject: "Rejection notification",
    dataAction: "send",
    taskName: "Send account opening rejection notification",
    input: "Rejection or compliance review outcome",
    output: "Customer rejection notification sent",
    defaultNextStep: "C026",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Notification delivery failure",
    exceptionHandling: "Notify RM for manual follow-up",
    sla: "Immediate",
    riskControl: "Notification wording follows compliance guidance",
    sourceRef: "CAO-NOTIFY-025",
    reviewStatus: "draft",
    comment: "",
    customerInteractionType: "Front-stage System",
    channel: "Email"
  },
  {
    id: "corp-account-026",
    stepId: "C026",
    parentStepId: "C025",
    rowType: "end",
    bpmnType: "endEvent",
    taskNature: "automatic",
    phase: "Final Approval",
    group: "Rejected End",
    actor: "System",
    actorLane: "System",
    system: "Onboarding Workflow",
    systemLane: "Workflow",
    dataObject: "Corporate account opening case",
    dataAction: "update",
    taskName: "Corporate account opening rejected",
    input: "Rejection notification sent",
    output: "Case closed as rejected",
    defaultNextStep: null,
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Rejected case is retained for audit",
    sourceRef: "CAO-END-026",
    reviewStatus: "draft",
    comment: "Rejected end state",
    customerInteractionType: "Support Process",
    channel: "Internal System"
  }
];

export default corporateAccountOpeningProcessTasks;
