import type { ProcessTask } from "@/lib/models/process-task";
import type { TemplateProfile } from "@/lib/models/template-profile";
import type { Workspace } from "@/lib/models/workspace";

export const sampleWorkspace: Workspace = {
  id: "workspace-sme-online-loan",
  name: "SME Online Loan Workbench",
  description: "Sample workspace for an SME online loan origination journey.",
  scope:
    "From online application submission to blacklist screening, supplement request, credit decision, and approval or rejection notification.",
  selectedBpmnTemplateId: "template-bpmn-sme-online-loan",
  selectedServiceBlueprintTemplateId: "template-service-blueprint-sme-online-loan",
  createdAt: "2026-05-06T00:00:00.000Z",
  updatedAt: "2026-05-06T00:00:00.000Z"
};

export const sampleBpmnTemplateProfile: TemplateProfile = {
  id: "template-bpmn-sme-online-loan",
  name: "BPMN Hybrid Actor-System-Data Lanes",
  type: "bpmn",
  version: "1.0.0",
  status: "active",
  outputType: "BPMN",
  processType: "Lending",
  journeyType: "Internal Workflow",
  scopeType: "End-to-end",
  businessDomain: "Banking",
  notationStandard: "BPMN 2.0",
  organizationType: "Bank",
  tags: ["SME lending", "loan origination", "BPMN"],
  laneRules: {
    lanes: ["Customer", "RM", "Ops Support", "Credit Approver", "System"]
  },
  rowRules: {
    allowedRowTypes: ["event", "task", "gateway", "data"]
  },
  taskCardRules: {
    showActor: true,
    showSystem: true,
    showSla: true,
    showRiskControl: true
  },
  connectorRules: {
    defaultNextStep: "solid",
    conditionalNextStep: "labeled"
  },
  colorRules: {
    event: "green",
    task: "blue",
    gateway: "amber",
    data: "gray"
  },
  layoutRules: {
    direction: "left-to-right",
    preserveActorSystemAdjacency: true
  },
  mandatoryFields: ["id", "stepId", "rowType", "bpmnType", "taskName", "reviewStatus"]
};

export const sampleServiceBlueprintTemplateProfile: TemplateProfile = {
  id: "template-service-blueprint-sme-online-loan",
  name: "Service Blueprint Container Task Card",
  type: "serviceBlueprint",
  version: "1.0.0",
  status: "active",
  outputType: "Service Blueprint",
  processType: "Lending",
  journeyType: "Customer Journey",
  scopeType: "End-to-end",
  businessDomain: "Banking",
  notationStandard: "Service Blueprint",
  organizationType: "Bank",
  tags: ["SME lending", "customer journey", "service blueprint"],
  laneRules: {
    customerLane: "Customer",
    frontstageLanes: ["RM"],
    backstageLanes: ["Ops Support", "Credit Approver"],
    supportLanes: ["System"]
  },
  rowRules: {
    preserveJourneyOrder: true,
    allowSupportDataRows: true,
    rows: [
      "STEPS",
      "PHASE",
      "TIME",
      "EVIDENCE",
      "CUSTOMER ACTIONS",
      "FRONT-STAGE INTERACTIONS — PEOPLE",
      "FRONT-STAGE INTERACTIONS — SYSTEM / CHANNEL",
      "BACK-STAGE INTERACTIONS — PEOPLE",
      "BACK-STAGE INTERACTIONS — SYSTEM / TOOLS",
      "SUPPORT PROCESSES",
      "DATA / CONTROL",
      "OUTCOME / END STATE"
    ]
  },
  taskCardRules: {
    showInputOutput: true,
    showExceptionHandling: true
  },
  connectorRules: {
    showLineOfInteraction: true,
    showLineOfVisibility: true,
    showSystemLinks: true
  },
  colorRules: {
    customer: "teal",
    frontstage: "blue",
    backstage: "violet",
    support: "slate"
  },
  layoutRules: {
    direction: "top-to-bottom",
    keepDataInteractionsAttachedToTasks: true
  },
  mandatoryFields: ["id", "stepId", "actorLane", "taskName", "input", "output"]
};

export const sampleProcessTasks: ProcessTask[] = [
  {
    id: "task-000",
    stepId: "S000",
    parentStepId: null,
    rowType: "event",
    bpmnType: "startEvent",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Start",
    customerInteractionType: "Support Process",
    channel: "Portal",
    actor: "System",
    actorLane: "System",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "",
    dataAction: "none",
    taskName: "Online loan journey starts",
    input: "SME customer enters online loan journey",
    output: "Journey start event",
    defaultNextStep: "S001",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "",
    sourceRef: "SME-OL-START-000",
    reviewStatus: "draft",
    comment: "Start Event only; no business action mixed into the event"
  },
  {
    id: "task-001",
    stepId: "S001",
    parentStepId: "S000",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Application Intake",
    group: "Start",
    customerInteractionType: "Customer Action",
    channel: "Portal",
    actor: "Customer",
    actorLane: "Customer",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Loan application session",
    dataAction: "create",
    taskName: "Customer starts online loan application",
    input: "Customer selects SME loan product",
    output: "New application session created",
    defaultNextStep: "S002",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Portal unavailable",
    exceptionHandling: "Show maintenance message and ask customer to retry later",
    sla: "Immediate",
    riskControl: "Session tracking enabled",
    sourceRef: "SME-OL-INTAKE-001",
    reviewStatus: "draft",
    comment: "Customer User Task after journey start event"
  },
  {
    id: "task-002",
    stepId: "S002",
    parentStepId: "S001",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Application Intake",
    group: "Customer Submission",
    customerInteractionType: "Customer Action",
    channel: "Portal",
    actor: "Customer",
    actorLane: "Customer",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Borrower profile",
    dataAction: "push",
    taskName: "Customer enters business and owner information",
    input: "Business registration, owner identity, contact information",
    output: "Borrower profile captured",
    defaultNextStep: "S003",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Mandatory fields missing",
    exceptionHandling: "Highlight missing fields before submission",
    sla: "Customer driven",
    riskControl: "Field validation and consent capture",
    sourceRef: "SME-OL-INTAKE-002",
    reviewStatus: "draft",
    comment: "User Task"
  },
  {
    id: "task-003",
    stepId: "S003",
    parentStepId: "S002",
    rowType: "data",
    bpmnType: "dataObject",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Data Capture",
    customerInteractionType: "Data / Control",
    channel: "Portal",
    actor: "System",
    actorLane: "System",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Borrower profile",
    dataAction: "store",
    taskName: "Portal stores borrower profile",
    input: "Submitted borrower profile",
    output: "Borrower profile persisted",
    defaultNextStep: "S004",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Save failed",
    exceptionHandling: "Keep draft and notify customer to retry",
    sla: "Immediate",
    riskControl: "Encrypted storage",
    sourceRef: "SME-OL-DATA-003",
    reviewStatus: "draft",
    comment: "Data interaction tied to customer submission"
  },
  {
    id: "task-004",
    stepId: "S004",
    parentStepId: "S003",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Application Intake",
    group: "Customer Submission",
    customerInteractionType: "Customer Action",
    channel: "Portal",
    actor: "Customer",
    actorLane: "Customer",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Financial documents",
    dataAction: "push",
    taskName: "Customer uploads financial documents",
    input: "Bank statements, tax documents, financial statements",
    output: "Documents uploaded",
    defaultNextStep: "S005",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Unsupported file format",
    exceptionHandling: "Reject file and show accepted formats",
    sla: "Customer driven",
    riskControl: "File type and malware scan",
    sourceRef: "SME-OL-INTAKE-004",
    reviewStatus: "draft",
    comment: "User Task"
  },
  {
    id: "task-005",
    stepId: "S005",
    parentStepId: "S004",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Validation",
    actor: "System",
    actorLane: "System",
    system: "Document Service",
    systemLane: "System",
    dataObject: "Financial documents",
    dataAction: "read",
    taskName: "System validates uploaded documents",
    input: "Uploaded documents",
    output: "Document validation result",
    defaultNextStep: "S006",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Document service timeout",
    exceptionHandling: "Queue validation retry",
    sla: "2 minutes",
    riskControl: "Virus scan and document checksum",
    sourceRef: "SME-OL-VALID-005",
    reviewStatus: "draft",
    comment: "Service Task"
  },
  {
    id: "task-006",
    stepId: "S006",
    parentStepId: "S005",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Completeness Check",
    actor: "System",
    actorLane: "System",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Application checklist",
    dataAction: "read",
    taskName: "Is application complete?",
    input: "Borrower profile and document validation result",
    output: "Completeness decision",
    defaultNextStep: null,
    conditionQuestion: "Are all mandatory fields and documents complete?",
    yesNextStep: "S010",
    noNextStep: "S007",
    exception: "Checklist cannot be evaluated",
    exceptionHandling: "Route to Ops Support manual review",
    sla: "Immediate",
    riskControl: "Mandatory field checklist",
    sourceRef: "SME-OL-GW-006",
    reviewStatus: "draft",
    comment: "Exclusive Gateway"
  },
  {
    id: "task-007",
    stepId: "S007",
    parentStepId: "S006",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Application Intake",
    group: "Supplement Request",
    customerInteractionType: "Front-stage People",
    channel: "Phone Call",
    actor: "RM",
    actorLane: "RM",
    system: "CRM",
    systemLane: "System",
    dataObject: "Supplement request",
    dataAction: "store",
    taskName: "RM creates supplementary information request",
    input: "Missing information list",
    output: "Supplement request created",
    defaultNextStep: "S031",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Missing reason unclear",
    exceptionHandling: "RM reviews checklist and clarifies missing items",
    sla: "4 business hours",
    riskControl: "RM review before sending request",
    sourceRef: "SME-OL-SUPP-007",
    reviewStatus: "draft",
    comment: "RM prepares supplement request before notification"
  },
  {
    id: "task-031",
    stepId: "S031",
    parentStepId: "S007",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Supplement Request",
    customerInteractionType: "Front-stage System",
    channel: "Email",
    actor: "System",
    actorLane: "System",
    system: "Notification Service",
    systemLane: "System",
    dataObject: "Supplement request notification",
    dataAction: "push",
    taskName: "Notification service sends supplementary request to customer",
    input: "Supplement request created by RM",
    output: "Supplement request notification sent",
    defaultNextStep: "S032",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Customer contact invalid",
    exceptionHandling: "RM calls customer and updates contact detail",
    sla: "Immediate",
    riskControl: "Notification delivery log",
    sourceRef: "SME-OL-SUPP-031",
    reviewStatus: "draft",
    comment: "System notification for supplement request"
  },
  {
    id: "task-032",
    stepId: "S032",
    parentStepId: "S031",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Supplement Request",
    actor: "System",
    actorLane: "System",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Supplement response status",
    dataAction: "read",
    taskName: "Did customer supplement within SLA or max attempts?",
    input: "Supplement request status, SLA deadline, attempt counter",
    output: "Supplement continuation decision",
    defaultNextStep: null,
    conditionQuestion: "Did the customer provide required supplements within SLA and max attempts?",
    yesNextStep: "S008",
    noNextStep: "S028",
    exception: "SLA status unavailable",
    exceptionHandling: "Route to Ops Support to confirm response status",
    sla: "3 business days",
    riskControl: "Max attempt and timeout policy",
    sourceRef: "SME-OL-SUPP-032",
    reviewStatus: "draft",
    comment: "Timeout or max-attempt path closes to rejection handling"
  },
  {
    id: "task-008",
    stepId: "S008",
    parentStepId: "S032",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Application Intake",
    group: "Supplement Request",
    actor: "Customer",
    actorLane: "Customer",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Supplement documents",
    dataAction: "push",
    taskName: "Customer provides supplementary information",
    input: "Supplement request",
    output: "Supplement information submitted",
    defaultNextStep: "S009",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Customer does not respond",
    exceptionHandling: "System follows timeout and max-attempt path through S032",
    sla: "3 business days",
    riskControl: "Customer consent and audit trail",
    sourceRef: "SME-OL-SUPP-008",
    reviewStatus: "draft",
    comment: "Customer supplement task"
  },
  {
    id: "task-009",
    stepId: "S009",
    parentStepId: "S008",
    rowType: "data",
    bpmnType: "dataObject",
    taskNature: "automatic",
    phase: "Application Intake",
    group: "Data Capture",
    customerInteractionType: "Data / Control",
    channel: "Portal",
    actor: "System",
    actorLane: "System",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Supplement documents",
    dataAction: "update",
    taskName: "Portal updates application with supplements",
    input: "Supplement information submitted",
    output: "Application checklist updated",
    defaultNextStep: "S006",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Update failed",
    exceptionHandling: "Keep upload draft and alert support",
    sla: "Immediate",
    riskControl: "Versioned document storage",
    sourceRef: "SME-OL-DATA-009",
    reviewStatus: "draft",
    comment: "Loops back to completeness gateway"
  },
  {
    id: "task-010",
    stepId: "S010",
    parentStepId: "S006",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Pre-check",
    group: "Blacklist Screening",
    actor: "System",
    actorLane: "System",
    system: "Risk Screening Engine",
    systemLane: "System",
    dataObject: "Customer identity and business registration",
    dataAction: "pull",
    taskName: "System performs blacklist screening",
    input: "Identity, business registration, owner details",
    output: "Blacklist screening result",
    defaultNextStep: "S011",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Screening provider unavailable",
    exceptionHandling: "Retry and route to Ops Support if still unavailable",
    sla: "5 minutes",
    riskControl: "Sanctions and internal blacklist checks",
    sourceRef: "SME-OL-RISK-010",
    reviewStatus: "draft",
    comment: "Service Task for blacklist/pre-check"
  },
  {
    id: "task-011",
    stepId: "S011",
    parentStepId: "S010",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "automatic",
    phase: "Pre-check",
    group: "Blacklist Screening",
    actor: "System",
    actorLane: "System",
    system: "Risk Screening Engine",
    systemLane: "System",
    dataObject: "Blacklist screening result",
    dataAction: "read",
    taskName: "Is applicant blacklisted?",
    input: "Blacklist screening result",
    output: "Blacklist decision",
    defaultNextStep: null,
    conditionQuestion: "Does any applicant or beneficial owner match blacklist rules?",
    yesNextStep: "S028",
    noNextStep: "S012",
    exception: "Ambiguous match",
    exceptionHandling: "Route to Ops Support for manual match review",
    sla: "Immediate",
    riskControl: "False-positive review threshold",
    sourceRef: "SME-OL-GW-011",
    reviewStatus: "draft",
    comment: "Exclusive Gateway"
  },
  {
    id: "task-012",
    stepId: "S012",
    parentStepId: "S011",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Pre-check",
    group: "Eligibility",
    actor: "System",
    actorLane: "System",
    system: "Credit Rules Engine",
    systemLane: "System",
    dataObject: "Application data",
    dataAction: "read",
    taskName: "System runs eligibility pre-check",
    input: "Application data and blacklist decision",
    output: "Eligibility result",
    defaultNextStep: "S013",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Rules engine unavailable",
    exceptionHandling: "Queue pre-check retry",
    sla: "5 minutes",
    riskControl: "Policy rule version control",
    sourceRef: "SME-OL-RULE-012",
    reviewStatus: "draft",
    comment: "Service Task"
  },
  {
    id: "task-013",
    stepId: "S013",
    parentStepId: "S012",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "automatic",
    phase: "Pre-check",
    group: "Eligibility",
    actor: "System",
    actorLane: "System",
    system: "Credit Rules Engine",
    systemLane: "System",
    dataObject: "Eligibility result",
    dataAction: "read",
    taskName: "Does application pass pre-check?",
    input: "Eligibility result",
    output: "Pre-check decision",
    defaultNextStep: null,
    conditionQuestion: "Does the application meet basic SME loan eligibility rules?",
    yesNextStep: "S014",
    noNextStep: "S028",
    exception: "Policy result incomplete",
    exceptionHandling: "Route to Ops Support for exception review",
    sla: "Immediate",
    riskControl: "Policy fail reasons retained",
    sourceRef: "SME-OL-GW-013",
    reviewStatus: "draft",
    comment: "Exclusive Gateway"
  },
  {
    id: "task-014",
    stepId: "S014",
    parentStepId: "S013",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Pre-check",
    group: "RM Review",
    customerInteractionType: "Back-stage People",
    channel: "LOS",
    actor: "RM",
    actorLane: "RM",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Application case",
    dataAction: "read",
    taskName: "RM reviews application summary",
    input: "Application case and pre-check result",
    output: "RM review notes",
    defaultNextStep: "S015",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "RM capacity unavailable",
    exceptionHandling: "Reassign case to backup RM",
    sla: "1 business day",
    riskControl: "RM maker role only",
    sourceRef: "SME-OL-RM-014",
    reviewStatus: "draft",
    comment: "RM task"
  },
  {
    id: "task-015",
    stepId: "S015",
    parentStepId: "S014",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Underwriting",
    group: "Ops Verification",
    actor: "Ops Support",
    actorLane: "Ops Support",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "KYC and document package",
    dataAction: "read",
    taskName: "Ops Support verifies KYC and documents",
    input: "Application case, KYC data, uploaded documents",
    output: "Verification result",
    defaultNextStep: "S016",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Document inconsistency found",
    exceptionHandling: "Send case back to RM for clarification",
    sla: "1 business day",
    riskControl: "Four-eye document verification",
    sourceRef: "SME-OL-OPS-015",
    reviewStatus: "draft",
    comment: "Ops Support task"
  },
  {
    id: "task-016",
    stepId: "S016",
    parentStepId: "S015",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Underwriting",
    group: "Ops Verification",
    actor: "Ops Support",
    actorLane: "Ops Support",
    system: "Core Banking",
    systemLane: "System",
    dataObject: "Existing customer exposure",
    dataAction: "pull",
    taskName: "Ops Support pulls existing exposure data",
    input: "Customer identifier",
    output: "Existing exposure and repayment history",
    defaultNextStep: "S017",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Core banking data unavailable",
    exceptionHandling: "Ops Support requests system retry or manual report",
    sla: "2 hours",
    riskControl: "Read-only core banking access",
    sourceRef: "SME-OL-DATA-016",
    reviewStatus: "draft",
    comment: "Manual Ops task preserving Ops-Core Banking link"
  },
  {
    id: "task-017",
    stepId: "S017",
    parentStepId: "S016",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Underwriting",
    group: "Credit Scoring",
    customerInteractionType: "Back-stage System",
    channel: "Internal System",
    actor: "System",
    actorLane: "System",
    system: "Credit Scoring Engine",
    systemLane: "System",
    dataObject: "Scoring dataset",
    dataAction: "read",
    taskName: "System calculates credit score",
    input: "Application data, documents, exposure data",
    output: "Credit score and risk grade",
    defaultNextStep: "S018",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Score cannot be calculated",
    exceptionHandling: "Route to manual underwriting",
    sla: "10 minutes",
    riskControl: "Model version and score audit trail",
    sourceRef: "SME-OL-SCORE-017",
    reviewStatus: "draft",
    comment: "Service Task"
  },
  {
    id: "task-018",
    stepId: "S018",
    parentStepId: "S017",
    rowType: "data",
    bpmnType: "dataObject",
    taskNature: "automatic",
    phase: "Underwriting",
    group: "Credit Scoring",
    customerInteractionType: "Data / Control",
    channel: "LOS",
    actor: "System",
    actorLane: "System",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Credit score and risk grade",
    dataAction: "store",
    taskName: "LOS stores credit score and risk grade",
    input: "Credit score and risk grade",
    output: "Scoring result attached to case",
    defaultNextStep: "S019",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Storage failed",
    exceptionHandling: "Retry and alert system support",
    sla: "Immediate",
    riskControl: "Immutable score snapshot",
    sourceRef: "SME-OL-DATA-018",
    reviewStatus: "draft",
    comment: "Data interaction"
  },
  {
    id: "task-019",
    stepId: "S019",
    parentStepId: "S018",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "semiAutomatic",
    phase: "Underwriting",
    group: "Credit Memo",
    actor: "RM",
    actorLane: "RM",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Credit memo",
    dataAction: "update",
    taskName: "RM prepares credit proposal",
    input: "Verified case and scoring result",
    output: "Credit proposal submitted",
    defaultNextStep: "S020",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Proposal information incomplete",
    exceptionHandling: "RM updates missing proposal fields",
    sla: "1 business day",
    riskControl: "RM cannot approve own proposal",
    sourceRef: "SME-OL-RM-019",
    reviewStatus: "draft",
    comment: "Semi-automatic task"
  },
  {
    id: "task-020",
    stepId: "S020",
    parentStepId: "S019",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "semiAutomatic",
    phase: "Underwriting",
    group: "Credit Memo",
    actor: "RM",
    actorLane: "RM",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Credit proposal",
    dataAction: "push",
    taskName: "RM submits proposal to Credit Approver",
    input: "Completed credit proposal",
    output: "Approval task created",
    defaultNextStep: "S021",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Approver queue unavailable",
    exceptionHandling: "Assign to alternate approver queue",
    sla: "Immediate",
    riskControl: "Segregation of duties",
    sourceRef: "SME-OL-RM-020",
    reviewStatus: "draft",
    comment: "Send Task"
  },
  {
    id: "task-021",
    stepId: "S021",
    parentStepId: "S020",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Decision",
    group: "Credit Approval",
    actor: "Credit Approver",
    actorLane: "Credit Approver",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Credit proposal",
    dataAction: "read",
    taskName: "Credit Approver reviews proposal",
    input: "Credit proposal, documents, score, Ops verification",
    output: "Credit decision recommendation",
    defaultNextStep: "S022",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Approver needs clarification",
    exceptionHandling: "Return case to RM with comment",
    sla: "1 business day",
    riskControl: "Approver authority matrix",
    sourceRef: "SME-OL-APP-021",
    reviewStatus: "draft",
    comment: "Credit Approver task"
  },
  {
    id: "task-022",
    stepId: "S022",
    parentStepId: "S021",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "manual",
    phase: "Decision",
    group: "Credit Approval",
    actor: "Credit Approver",
    actorLane: "Credit Approver",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Credit decision",
    dataAction: "update",
    taskName: "Is loan approved?",
    input: "Credit decision recommendation",
    output: "Approval decision",
    defaultNextStep: null,
    conditionQuestion: "Does the Credit Approver approve the loan?",
    yesNextStep: "S023",
    noNextStep: "S028",
    exception: "Decision outside authority",
    exceptionHandling: "Escalate to higher approval authority",
    sla: "Immediate",
    riskControl: "Authority matrix validation",
    sourceRef: "SME-OL-GW-022",
    reviewStatus: "draft",
    comment: "Exclusive Gateway"
  },
  {
    id: "task-023",
    stepId: "S023",
    parentStepId: "S022",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Decision",
    group: "Offer Generation",
    actor: "System",
    actorLane: "System",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Loan offer",
    dataAction: "store",
    taskName: "System generates approved loan offer",
    input: "Approved decision and pricing terms",
    output: "Loan offer generated",
    defaultNextStep: "S024",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Offer generation failed",
    exceptionHandling: "Retry generation and alert Ops Support",
    sla: "5 minutes",
    riskControl: "Approved terms locked",
    sourceRef: "SME-OL-OFFER-023",
    reviewStatus: "draft",
    comment: "Service Task"
  },
  {
    id: "task-024",
    stepId: "S024",
    parentStepId: "S023",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "automatic",
    phase: "Decision",
    group: "Customer Notification",
    customerInteractionType: "Front-stage System",
    channel: "Email",
    actor: "System",
    actorLane: "System",
    system: "Notification Service",
    systemLane: "System",
    dataObject: "Approval notification",
    dataAction: "push",
    taskName: "System sends approval notification",
    input: "Loan offer",
    output: "Approval notification sent",
    defaultNextStep: "S025",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Notification delivery failed",
    exceptionHandling: "Retry notification and create RM follow-up task",
    sla: "Immediate",
    riskControl: "Notification delivery log",
    sourceRef: "SME-OL-NOTIFY-024",
    reviewStatus: "draft",
    comment: "Send Task"
  },
  {
    id: "task-025",
    stepId: "S025",
    parentStepId: "S024",
    rowType: "task",
    bpmnType: "userTask",
    taskNature: "manual",
    phase: "Decision",
    group: "Customer Acceptance",
    actor: "Customer",
    actorLane: "Customer",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Loan offer",
    dataAction: "read",
    taskName: "Customer reviews approved loan offer",
    input: "Approval notification and loan offer",
    output: "Customer acceptance or no action",
    defaultNextStep: "S033",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Customer cannot access offer",
    exceptionHandling: "RM assists customer and verifies identity",
    sla: "5 business days",
    riskControl: "Offer expiry date",
    sourceRef: "SME-OL-CUST-025",
    reviewStatus: "draft",
    comment: "Customer task after approval"
  },
  {
    id: "task-033",
    stepId: "S033",
    parentStepId: "S025",
    rowType: "gateway",
    bpmnType: "exclusiveGateway",
    taskNature: "decision",
    phase: "Decision",
    group: "Customer Acceptance",
    actor: "Customer",
    actorLane: "Customer",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Customer offer decision",
    dataAction: "read",
    taskName: "Customer accepts offer?",
    input: "Customer review outcome",
    output: "Customer offer decision",
    defaultNextStep: null,
    conditionQuestion: "Does the customer accept the approved loan offer?",
    yesNextStep: "S026",
    noNextStep: "S034",
    exception: "Customer decision not captured",
    exceptionHandling: "Keep offer pending until expiry policy applies",
    sla: "5 business days",
    riskControl: "Offer expiry and acceptance audit trail",
    sourceRef: "SME-OL-CUST-033",
    reviewStatus: "draft",
    comment: "Offer acceptance gateway"
  },
  {
    id: "task-026",
    stepId: "S026",
    parentStepId: "S033",
    rowType: "data",
    bpmnType: "dataObject",
    taskNature: "automatic",
    phase: "Decision",
    group: "Customer Acceptance",
    customerInteractionType: "Data / Control",
    channel: "Portal",
    actor: "System",
    actorLane: "System",
    system: "Digital Lending Portal",
    systemLane: "System",
    dataObject: "Customer acceptance record",
    dataAction: "store",
    taskName: "Portal stores customer offer acceptance",
    input: "Customer acceptance action",
    output: "Acceptance record stored",
    defaultNextStep: "S027",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Acceptance save failed",
    exceptionHandling: "Ask customer to retry and notify RM",
    sla: "Immediate",
    riskControl: "Timestamp and IP audit trail",
    sourceRef: "SME-OL-DATA-026",
    reviewStatus: "draft",
    comment: "Data interaction tied to customer offer review"
  },
  {
    id: "task-027",
    stepId: "S027",
    parentStepId: "S026",
    rowType: "event",
    bpmnType: "endEvent",
    taskNature: "automatic",
    phase: "Decision",
    group: "Approved End",
    customerInteractionType: "Support Process",
    channel: "LOS",
    actor: "System",
    actorLane: "System",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Approved application",
    dataAction: "none",
    taskName: "Loan application ends as approved",
    input: "Accepted loan offer",
    output: "Approved end state",
    defaultNextStep: null,
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Final state audit trail",
    sourceRef: "SME-OL-END-027",
    reviewStatus: "draft",
    comment: "Approval End Event"
  },
  {
    id: "task-034",
    stepId: "S034",
    parentStepId: "S033",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Decision",
    group: "Customer Acceptance",
    customerInteractionType: "Data / Control",
    channel: "LOS",
    actor: "System",
    actorLane: "System",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Customer rejection record",
    dataAction: "store",
    taskName: "System records customer rejection",
    input: "Customer declined offer",
    output: "Customer rejection reason stored",
    defaultNextStep: "S035",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Rejection reason missing",
    exceptionHandling: "Store declined status with default customer rejection reason",
    sla: "Immediate",
    riskControl: "Final decision audit trail",
    sourceRef: "SME-OL-CUST-034",
    reviewStatus: "draft",
    comment: "Customer declined approved offer"
  },
  {
    id: "task-035",
    stepId: "S035",
    parentStepId: "S034",
    rowType: "event",
    bpmnType: "endEvent",
    taskNature: "automatic",
    phase: "Decision",
    group: "Customer Rejection End",
    customerInteractionType: "Support Process",
    channel: "LOS",
    actor: "System",
    actorLane: "System",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Customer rejected application",
    dataAction: "none",
    taskName: "Loan application ends as customer rejected",
    input: "Customer rejection record",
    output: "Customer rejection end state",
    defaultNextStep: null,
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Final state audit trail",
    sourceRef: "SME-OL-END-035",
    reviewStatus: "draft",
    comment: "Customer rejection End Event"
  },
  {
    id: "task-028",
    stepId: "S028",
    parentStepId: "S022",
    rowType: "task",
    bpmnType: "serviceTask",
    taskNature: "automatic",
    phase: "Decision",
    group: "Rejection Handling",
    customerInteractionType: "Data / Control",
    channel: "LOS",
    actor: "System",
    actorLane: "System",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Rejection reason",
    dataAction: "store",
    taskName: "System records rejection reason",
    input: "Blacklist, pre-check, or approver rejection reason",
    output: "Rejection reason stored",
    defaultNextStep: "S029",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Reason code missing",
    exceptionHandling: "Require reason code before closing case",
    sla: "Immediate",
    riskControl: "Reason code taxonomy",
    sourceRef: "SME-OL-REJECT-028",
    reviewStatus: "draft",
    comment: "Shared rejection path"
  },
  {
    id: "task-029",
    stepId: "S029",
    parentStepId: "S028",
    rowType: "task",
    bpmnType: "sendTask",
    taskNature: "automatic",
    phase: "Decision",
    group: "Customer Notification",
    customerInteractionType: "Front-stage System",
    channel: "Email",
    actor: "System",
    actorLane: "System",
    system: "Notification Service",
    systemLane: "System",
    dataObject: "Rejection notification",
    dataAction: "push",
    taskName: "System sends rejection notification",
    input: "Rejection reason",
    output: "Rejection notification sent",
    defaultNextStep: "S030",
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "Notification delivery failed",
    exceptionHandling: "Retry notification and create RM follow-up task",
    sla: "Immediate",
    riskControl: "Customer-safe reason wording",
    sourceRef: "SME-OL-NOTIFY-029",
    reviewStatus: "draft",
    comment: "Send Task"
  },
  {
    id: "task-030",
    stepId: "S030",
    parentStepId: "S029",
    rowType: "event",
    bpmnType: "endEvent",
    taskNature: "automatic",
    phase: "Decision",
    group: "Rejected End",
    customerInteractionType: "Support Process",
    channel: "LOS",
    actor: "System",
    actorLane: "System",
    system: "Loan Origination System",
    systemLane: "System",
    dataObject: "Rejected application",
    dataAction: "none",
    taskName: "Loan application ends as rejected",
    input: "Rejection notification sent",
    output: "Rejected end state",
    defaultNextStep: null,
    conditionQuestion: "",
    yesNextStep: null,
    noNextStep: null,
    exception: "",
    exceptionHandling: "",
    sla: "Immediate",
    riskControl: "Final state audit trail",
    sourceRef: "SME-OL-END-030",
    reviewStatus: "draft",
    comment: "Reject End Event"
  }
];
